include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - lib/injection.config.dart
    - lib/generated_plugin_registrant.dart
  errors:
    # missing_required_param: error
    invalid_assignment: ignore
    unnecessary_this: ignore
    unnecessary_getters_setters: ignore
    avoid_print: ignore
    sort_pub_dependencies: ignore
    avoid_multiple_declarations_per_line: ignore
    leading_newlines_in_multiline_strings: ignore
    avoid_void_async: ignore
    # missing_return: error
    # must_be_immutable: error
    # sort_unnamed_constructors_first: ignore
    depend_on_referenced_packages: ignore
    prefer_const_literals_to_create_immutables: ignore
    always_use_package_imports: ignore
    # argument_type_not_assignable: ignore
    # sized_box_for_whitespace: ignore
    # void_checks: ignore
